require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  Exclude:
    - "bin/*"
    - "Guardfile"
    - "Rakefile"
    - "counter_cache.gemspec"

  DisplayCopNames: true

Metrics/LineLength:
  Max: 80
  IngorePatterns: ['(\A|\s)#']

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
